# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

#import scrapy
from scrapy.item import Item, Field

class BkstrItem(Item):
	course = Field()
	title1 = Field()
	author1 = Field()
	isbn1 = Field()
	year1 = Field()
	publisher1 = Field()
	#author2 = Field()
	#isbn2 = Field()
	#year2 = Field()
	#publisher2 = Field() 
	title2 = Field()
	title3 = Field()
	type1a = Field()
	type1b = Field()
	type1c = Field()
	type1d = Field()
	type1e = Field()
	type2a = Field()
	type2b = Field()
	type2c = Field()
	type2d = Field()
	type2e = Field()
	type3a = Field()
	type3b = Field()
	type3c = Field()
	type3d = Field()
	type3e = Field()
	buyrent1a = Field()
	buyrent1b = Field()
	buyrent1c = Field()
	buyrent1d = Field()
	buyrent1e = Field()
	buyrent2a = Field()
	buyrent2b = Field()
	buyrent2c = Field()
	buyrent2d = Field()
	buyrent2e = Field()
	buyrent3a = Field()
	buyrent3b = Field()
	buyrent3c = Field()
	buyrent3d = Field()
	buyrent3e = Field()
	option1a = Field()
	option1b = Field()
	option1c = Field()
	option1d = Field()
	option1e = Field()
	option2a = Field()
	option2b = Field()
	option2c = Field()
	option2d = Field()
	option2e = Field()
	option3a = Field()
	option3b = Field()
	option3c = Field()
	option3d = Field()
	option3e = Field()
	price1a = Field()
	price1b = Field()
	price1c = Field()
	price1d = Field()
	price1e = Field()
	price2a = Field()
	price2b = Field()
	price2c = Field()
	price2d = Field()
	price2e = Field()
	price3a = Field()
	price3b = Field()
	price3c = Field()
	price3d = Field()
	price3e = Field()
	pass		
	

